# Classical Gates
In this notebook, we will define and explore the logic operations known as gates, that make up our classical computational world. 
> A logic gate is an idealized model of computation or physical electronic device implementing a Boolean function, a logical operation performed on one or more binary inputs that produces a single binary output.

We can define gates by their action on a given bit, using a `truth table`.

## 1-Bit gates
1.  `BUFFER` Gate
The `BUFFER` gate is simply the identity operation, and is defined with the following `truth table`:

|Input | Output |
|--- | --- |
|0  |  0 |
|1  |  1 |

2.  `NOT` Gate
The `NOT` gate is simply a gate which will flip the bit it acts on. 
Also known as an inverter, the `NOT` gate has the following `truth table`:

|Input | Output |
|--- | --- |
|0  |  1 |
|1  |  0 |

<!--We can implement this boolean operation using something known as "[modular arithmetic](https://en.wikipedia.org/wiki/Modular_arithmetic)". -->

In [54]:
import montecarlo
import numpy as np
conf = montecarlo.SpinConfig1D(N=15)

print("1: ", conf)
conf.x_gate(8)

print("2: ", conf)
conf.x_gate(4)

print("3: ", conf)
conf.x_gate(8)

print("4: ", conf)

1:  000000000000000
2:  000000001000000
3:  000010001000000
4:  000010000000000


### Matrix representation
This is a 1-bit gate. Since the bit can be in 1 of 2 states, 
let's call the `on` state $\begin{pmatrix} 1 \\ 0 \end{pmatrix}$, 
and the `off` state $\begin{pmatrix} 0 \\ 1 \end{pmatrix}$.

Treating these states as vectors, we can find a matrix which implements the `X` gate:
$$\begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}$$

In [55]:
off = np.array([[1,0]]).T
on = np.array([[0,1]]).T
print("on: \n", on)
print("off:\n", off)

XGate = np.array([[0,1],[1,0]])
print("XGate")
print(XGate)
print("XGate applied to on state")
print(XGate.dot(on))
print("XGate applied to off state")
print(XGate.dot(off))

IGate = np.array([[1,0],[0,1]])
print("IGate")
print(IGate)
print("IGate applied to on state")
print(IGate.dot(on))
print("IGate applied to off state")
print(IGate.dot(off))

on: 
 [[0]
 [1]]
off:
 [[1]
 [0]]
XGate
[[0 1]
 [1 0]]
XGate applied to on state
[[1]
 [0]]
XGate applied to off state
[[0]
 [1]]
IGate
[[1 0]
 [0 1]]
IGate applied to on state
[[0]
 [1]]
IGate applied to off state
[[1]
 [0]]


## 2-Bit gates
1.  `AND` Gate
|Input | Output |
|---   | --- |
|00    |  0  |
|01    |  0  |
|10    |  0  |
|11    |  1  |

In [56]:
conf.x_gate(13)
conf.x_gate(6)
conf2 = montecarlo.SpinConfig1D(15)
conf2.set_int_config(458)
print("1:        ", conf)
print("2:        ", conf2)
print(" 1 and 2: ", conf.and_gate(conf2))

1:         000010100000010
2:         000000111001010
 1 and 2:  000000100000010


`off|off` = $\begin{pmatrix} 1 \\ 0 \\ 0 \\0 \end{pmatrix}$, 
`off|on` = $\begin{pmatrix} 0 \\ 1 \\ 0 \\0 \end{pmatrix}$, 
`on|off` = $\begin{pmatrix} 0 \\ 0 \\ 1 \\0 \end{pmatrix}$, 
`off|off` = $\begin{pmatrix} 0 \\ 0 \\ 0 \\1 \end{pmatrix}$, 

In [57]:
AndGate = np.array([[1, 1, 1, 0],[0, 0, 0, 1]])
print(AndGate)

offoff = np.array([[1, 0, 0, 0]]).T
offon =  np.array([[0, 1, 0, 0]]).T
onoff =  np.array([[0, 0, 1, 0]]).T
onon =   np.array([[0, 0, 0, 1]]).T

print("AndGate applied to off-off state")
print(AndGate.dot(offoff))
print("AndGate applied to on-off state")
print(AndGate.dot(onoff))
print("AndGate applied to off-on state")
print(AndGate.dot(offon))
print("AndGate applied to on-on state")
print(AndGate.dot(onon))

[[1 1 1 0]
 [0 0 0 1]]
AndGate applied to off-off state
[[1]
 [0]]
AndGate applied to on-off state
[[1]
 [0]]
AndGate applied to off-on state
[[1]
 [0]]
AndGate applied to on-on state
[[0]
 [1]]


2.  `OR`  Gate
|Input | Output |
|---   | --- |
|00    |  0  |
|01    |  1  |
|10    |  1  |
|11    |  1  |

3.  `NAND` Gate
|Input | Output |
|---   | --- |
|00    |  1  |
|01    |  1  |
|10    |  1  |
|11    |  0  |

4.  `NOR` Gate
|Input | Output |
|---   | --- |
|00    |  1  |
|01    |  0  |
|10    |  0  |
|11    |  0  |

5. `XOR` Gate
|Input | Output |
|---   | --- |
|00    |  0  |
|01    |  1  |
|10    |  1  |
|11    |  0  |

6. `XNOR` Gate
|Input | Output |
|---   | --- |
|00    |  1  |
|01    |  0  |
|10    |  0  |
|11    |  1  |

# `Quantum` Gates

Let's go back to the case where we had a single bit. 
Our `X_gate` was given as $\begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}$.
However, a quantum computer gives us access to new kinds of gates. 
There are many new quantum gates, but the first that is worth discussing is the 
`Hadamard` gate:
$$H = \frac{1}{\sqrt{2}}\begin{pmatrix} 1 & 1 \\ 1 & -1 \end{pmatrix}$$

Let's see what happens when this gate acts on a single bit of information:

In [58]:
HGate = np.array([[1, 1],[1, -1]])/np.sqrt(2)
print(HGate)

print("HGate applied to off state")
print(HGate.dot(off))
print("HGate applied to on state")
print(HGate.dot(on))

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
HGate applied to off state
[[0.70710678]
 [0.70710678]]
HGate applied to on state
[[ 0.70710678]
 [-0.70710678]]


As we see, this gate does something special, it creates a `superposition`!

`off` $\rightarrow \frac{1}{\sqrt{2}}$(`on` + `off`) 

`on` $\rightarrow \frac{1}{\sqrt{2}}$(`on` - `off`) 