# Gates

## Classical Gates

In this notebook, we will define and explore the logic operations known as gates, that make up our classical computational world. 
> A logic gate is an idealized model of computation or physical electronic device implementing a Boolean function, a logical operation performed on one or more binary inputs that produces a single binary output.

We can define gates by their action on a given bit, using a `truth table`.

### 1-Bit gates
1.  `BUFFER` Gate
The `BUFFER` gate is simply the identity operation, and is defined with the following `truth table`:

|Input | Output |
|--- | --- |
|0  |  0 |
|1  |  1 |

2.  `NOT` Gate
The `NOT` gate is simply a gate which will flip the bit it acts on. 
Also known as an inverter, the `NOT` gate has the following `truth table`:

|Input | Output |
|--- | --- |
|0  |  1 |
|1  |  0 |

#### Matrix representation
This is a 1-bit gate. Since the bit can be in 1 of 2 states, 
let's call the `off` state $\begin{pmatrix} 1 \\ 0 \end{pmatrix}$, 
and the `on` state $\begin{pmatrix} 0 \\ 1 \end{pmatrix}$.

Treating these states as vectors, we can find a matrix which implements the `X` gate:
$$\begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}$$
such that,
$$\begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}\begin{pmatrix} 1 \\ 0 \end{pmatrix} = \begin{pmatrix} 0 \\ 1 \end{pmatrix}$$
$$\begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}\begin{pmatrix} 0 \\ 1 \end{pmatrix} = \begin{pmatrix} 1 \\ 0 \end{pmatrix}$$



<!--We can implement this boolean operation using something known as "[modular arithmetic](https://en.wikipedia.org/wiki/Modular_arithmetic)". -->

### 2-Bit gates

These are classical gates that act on 2 bits at a time. Here are the truth tables:

1.  `AND` Gate
|Input | Output |
|---   | --- |
|00    |  0  |
|01    |  0  |
|10    |  0  |
|11    |  1  |
2.  `OR`  Gate
|Input | Output |
|---   | --- |
|00    |  0  |
|01    |  1  |
|10    |  1  |
|11    |  1  |

3.  `NAND` Gate
|Input | Output |
|---   | --- |
|00    |  1  |
|01    |  1  |
|10    |  1  |
|11    |  0  |

4.  `NOR` Gate
|Input | Output |
|---   | --- |
|00    |  1  |
|01    |  0  |
|10    |  0  |
|11    |  0  |

5. `XOR` Gate
|Input | Output |
|---   | --- |
|00    |  0  |
|01    |  1  |
|10    |  1  |
|11    |  0  |

6. `XNOR` Gate
|Input | Output |
|---   | --- |
|00    |  1  |
|01    |  0  |
|10    |  0  |
|11    |  1  |

## `Quantum` Gates

### 1-qubit Gates

#### Hadamard gate
Let's go back to the case where we had a single bit. 
Our `X_gate` was given as $\begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}$.
However, a quantum computer gives us access to new kinds of gates. 
There are many new quantum gates, but the first that is worth discussing is the 
`Hadamard` gate:
$$H = \frac{1}{\sqrt{2}}\begin{pmatrix} 1 & 1 \\ 1 & -1 \end{pmatrix}$$

Let's see what happens when this gate acts on a single bit of information:

In [11]:
import numpy as np
HGate = np.array([[1, 1],[1, -1]])/np.sqrt(2)
print(" Hadamard gate: ")
print(HGate)
print()

off = np.array([[1,0]]).T
on = np.array([[0,1]]).T

print(" |off> = ")
print(off)
print()
print(" |on> = ")
print(on)
print()

print("HGate applied to off state")
print(HGate.dot(off))
print()

print("HGate applied to on state")
print(HGate.dot(on))

 Hadamard gate: 
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

 |off> = 
[[1]
 [0]]

 |on> = 
[[0]
 [1]]

HGate applied to off state
[[0.70710678]
 [0.70710678]]

HGate applied to on state
[[ 0.70710678]
 [-0.70710678]]


As we see, this gate does something special, it creates a `superposition`!

$U^H\ket{0} = \frac{1}{\sqrt{2}}\left(\ket{0}+\ket{1}\right) = \ket{+}$

$U^H\ket{1} = \frac{1}{\sqrt{2}}\left(\ket{0}-\ket{1}\right) = \ket{-}$


#### Rotation gates

Any qubit state $\ket{\psi}$ can be written as a linear combination of the `off` and `on` states, $\ket{0}$ and $\ket{1}$: 
$$
\ket{\psi} = c_0\ket{0} + c_1\ket{1}
$$
Initially, this might look like we have 2 variables, or 2 degrees of freedom such that the space of all possible qubit states is a 2-dimensional plane. 
However, this is not the case, because we require that states be normalized. 
This means that the 2 variables are not independent, but rather are related by 
<!-- = \left(a_0 + ib_0\right)\ket{0} + \left(a_1 + ib_1\right)\ket{1}$$ -->
% where the $a$ and $b$ coefficients are just the real and imaginary components of the amplitudes $c_1$ and $c_2$. 

Initially this might look like a qubit lives in a 4-dimensional vector space (4 degrees of freedom). 
However, because we require that our wavefunction remains normalized, there are actually only 3 degrees of freedom. 
As such, the state of a qubit is perfectly represented as a vector 

In [12]:
from qiskit import *
from qiskit.tools.visualization import plot_histogram
from qiskit.tools.visualization import plot_bloch_multivector